server:
  port: 8087


spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_task_tracker
    username: root
    password: Galata97

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: samiraeyyubova08@gmail.com
    password: ssbowyqyuuwetsey

    properties.mail.smtp:
      auth: true
      starttls.enable: true


app:
  jwt:
    token:
      prefix: Bearer
    secret: asdsadsadsadsadasdasdsadsadsadasdasdasdsadasdasdasdsadadsadsadsadasdasdasdasdaasdddfdasdsadsadsadsadasdasdsaasdsadsadsadsadasdasdsa
    exp: 300000
    refresh: 1000000



